### ISSUE TITLE
compilation error on xenial

### ISSUE THREAD

**Issue by DarioTurchi** [ADLINK-IST/opensplice#87]
when trying to compile with Ubuntu 16.04, gcc 5.4.0, I get the following error:

```
/home/ida/Perception/data/opensplice/src/database/database/code/c_base.c: In function 'c__newBaseArrayObjectCommon':
/home/ida/Perception/data/opensplice/src/database/database/code/c_base.c:2024:35: error: 'struct c_collectionType_s' has no member named 'base'
                 c_header(arrayType->base->lastObject)->nextObject = o;
                                   ^
/home/ida/Perception/data/opensplice/src/database/database/include/c_typebase.h:45:38: note: in definition of macro 'C_ADDRESS'
 #define C_ADDRESS(ptr)  ((c_address)(ptr))
                                      ^
/home/ida/Perception/data/opensplice/src/database/database/code/c_base.c:2024:17: note: in expansion of macro 'c_header'
                 c_header(arrayType->base->lastObject)->nextObject = o;
```
Any idea about what the cause could be ?
